# Generated by Django 5.2 on 2025-04-11 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextThroughTweet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('target_word', models.CharField(max_length=255, unique=True)),
                ('target_word_position', models.IntegerField()),
                ('last_checked_at', models.DateTimeField()),
                ('tweet_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('author_id', models.BigIntegerField()),
                ('tweet_text', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TextTweetOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('ttt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_through_tweet.textthroughtweet')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_through_tweet.tweet')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('ttt', 'order')},
            },
        ),
    ]
