# Generated by Django 5.2 on 2025-04-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_through_tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textthroughtweet',
            name='ciphered_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='textthroughtweet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_text',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='TextTweetOrder',
        ),
    ]
